### PR TITLE
Fixing composite aggregations with correct parameters

### LINKED ISSUE #957: [BUG] The .order() method of aggregation does not work with composite aggregations
### What is the bug?
The .order() method of aggregation expects input parameters of Map<> or List<Map> type  only which throws error while doing the composite aggregation.

### How can one reproduce the bug?
` 
Aggregation aggregation = new Aggregation.Builder().terms(aggField -> aggField.field("my_name.keyword").order(Map.of("_key", SortOrder.Desc))).build();
`

This will throw an error when used with composite aggregation. Error:
`
[x_content_parse_exception] [1:125] [composite] failed to parse field [sources]
`
with this root cause
`
[1:137] [terms] order doesn't support values of type: START_ARRAY
`
                
### What is the expected behavior?
I think the .order() method should just accept string values too

### What is your host/environment?
Using opensearch-java library in my spring boot application

### Do you have any additional context?
Pls refer this stackoverflow link for detailed question:
[Link](https://stackoverflow.com/questions/78373328/how-to-sort-the-composite-aggregation-in-elasticsearch-opensearch)

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
Introduced classes for composite aggregations for terms, datehistogram, histogram and geotilegrid. I looked in the server code from https://github.com/opensearch-project/OpenSearch/tree/main/server/src/main/java/org/opensearch/search/aggregations/bucket/composite.

### Issues Resolved
Fixes #957 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
I am working on fixing/improving the test I added in this PR.

**Comment by VachaShah** [comment]
I am wondering if I missed something in the code or I am using it incorrectly in tests 🤔 Looking through server code, it looks like the code is matching but could use another pair of eyes. @dblock @reta

**Comment by dblock** [comment]
> I am wondering if I missed something in the code or I am using it incorrectly in tests 🤔 Looking through server code, it looks like the code is matching but could use another pair of eyes. @dblock @reta

Add a working sample to samples, maybe start an aggregations guide if we don't have anything n that, this way you know whether the code works?

Also do check what's available in https://github.com/opensearch-project/opensearch-api-specification for this, good opportunity to fix/add as we have an incoming code generator in #366.

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+
+public class CompositeDateHistogramAggregationSource extends CompositeValuesSource {
+
+    @Nullable
+    private final Time calendarInterval;
+
+    @Nullable
+    private final Time fixedInterval;
+
+    private final long offset;
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java:29]: `@Nullable` ?

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+
+    private final String zoneId;
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java:31]: `@Nullable`?

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+        implements
+            ObjectBuilder<CompositeDateHistogramAggregationSource> {
+
+        @Nullable
+        private Time calendarInterval;
+
+        @Nullable
+        private Time fixedInterval;
+
+        private long offset;
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java:119]: @Nullable?

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+
+        private String zoneId;
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java:121]: `@Nullable`

**Comment by reta** [comment]
Thanks @VachaShah , I think it looks good model wise

**Comment by VachaShah** [comment]
> > I am wondering if I missed something in the code or I am using it incorrectly in tests 🤔 Looking through server code, it looks like the code is matching but could use another pair of eyes. @dblock @reta
> 
> Add a working sample to samples, maybe start an aggregations guide if we don't have anything n that, this way you know whether the code works?
> 
> Also do check what's available in https://github.com/opensearch-project/opensearch-api-specification for this, good opportunity to fix/add as we have an incoming code generator in #366.

I will make sure to add samples and guides and will look through the specs as well!

**Comment by VachaShah** [comment]
> Thanks @VachaShah , I think it looks good model wise

Thanks @reta! Its weird why the test that I added doesn't fail here, it fails for me on my local 🤔

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java (hunk 2 above)
Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java:31]: The server doesn't allow nulls though https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DateHistogramValuesSourceBuilder.java#L262.

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java (hunk 3 above)
Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeDateHistogramAggregationSource.java:119]: Yeah this can be null I think, don't see any restrictions on the server end.

**Comment by reta** [comment]
> Thanks @reta! Its weird why the test that I added doesn't fail here, it fails for me on my local 🤔

Hm ... I am not sure, could look later on if you need a hand!

**Comment by VachaShah** [comment]
> > Thanks @reta! Its weird why the test that I added doesn't fail here, it fails for me on my local 🤔
> 
> Hm ... I am not sure, could look later on if you need a hand!

Thank you @reta! Yeah I still have test failures on my local but the workflows here are green, my failure is:

```
org.opensearch.client.opensearch.integTest.restclient.SearchRequestIT > shouldReturnSearchResultsWithCompositeAgg FAILED
    org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [x_content_parse_exception] [1:95] [composite] failed to parse field [sources]
        at __randomizedtesting.SeedInfo.seed([8D5592150CC0C93:3514B0F383EF841C]:0)
        at app//org.opensearch.client.transport.Endpoint.exceptionConverter(Endpoint.java:102)
        at app//org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:312)
        at app//org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:148)
        at app//org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1381)
        at app//org.opensearch.client.opensearch.integTest.AbstractSearchRequestIT.shouldReturnSearchResultsWithCompositeAgg(AbstractSearchRequestIT.java:88)
        at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
``` 

This is against OpenSearch 2.11.0. I will continue debugging into this.

**Comment by dblock** [comment]
@VachaShah One possible explanation would be that we're not actually running this integration test in CI/CD. Will you please try to make a change that shows which/how many tests are run? I see `Task :java-client:integrationTest` in the logs, but it doesn't show more detail.

**Comment by VachaShah** [comment]
> @VachaShah One possible explanation would be that we're not actually running this integration test in CI/CD. Will you please try to make a change that shows which/how many tests are run? I see `Task :java-client:integrationTest` in the logs, but it doesn't show more detail.

Yeah thats what is happening I think. Running `./gradlew :java-client:integrationTest --info`:

```
> Task :java-client:integrationTest
Caching disabled for task ':java-client:integrationTest' because:
  Build cache is disabled
Task ':java-client:integrationTest' is not up-to-date because:
  Value of input property 'systemProperties' has changed for task ':java-client:integrationTest'
Starting process 'Gradle Test Executor 1'. Working directory: /home/ubuntu/opensearch-java/java-client Command: /usr/lib/jvm/jdk-11.0.13+8/bin/java -Dhttps=true -Dorg.gradle.internal.worker.tmpdir=/home/ubuntu/opensearch-java/java-client/build/tmp/integrationTest/work -Dorg.gradle.native=false -Dpassword=admin -Dtests.awsSdk2support.domainHost -Dtests.awsSdk2support.domainRegion=us-east-1 -Dtests.awsSdk2support.serviceName=es -Dtests.security.manager=false -Duser=admin @/home/ubuntu/.gradle/.tmp/gradle-worker-classpath1009533041375880968txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'

org.opensearch.client.opensearch.integTest.aws.AwsSdk2BulkRequestIT > testBulkRequest SKIPPED

org.opensearch.client.opensearch.integTest.aws.AwsSdk2SearchIT > testAsyncClient SKIPPED

org.opensearch.client.opensearch.integTest.aws.AwsSdk2SearchIT > testSyncAsyncClient SKIPPED

org.opensearch.client.opensearch.integTest.aws.AwsSdk2SearchIT > testAsyncAsyncClient SKIPPED

org.opensearch.client.opensearch.integTest.aws.AwsSdk2SearchIT > testSyncClient SKIPPED

org.opensearch.client.opensearch.integTest.aws.AwsSdk2SearchIT > testDoubleWrappedException SKIPPED

org.opensearch.client.opensearch.integTest.aws.AwsSdk2SecurityIT > testUnAuthorizedException SKIPPED
Finished generating test XML results (0.011 secs) into: /home/ubuntu/opensearch-java/java-client/build/test-results/integrationTest
Generating HTML test report...
Finished generating test html results (0.016 secs) into: /home/ubuntu/opensearch-java/java-client/build/reports/tests/integrationTest
```

I will fix this in a separate PR first.

**Comment by reta** [comment]
> Ah I think the tests are only running from https://github.com/opensearch-project/opensearch-java/tree/main/java-client/src/test/java/org/opensearch/client and not from https://github.com/opensearch-project/opensearch-java/tree/main/java-client/src/test/java11/org/opensearch/client/opensearch/integTest

Thanks @VachaShah , I used to always run `./gradlew check` locally, which runs all tests, but indeed GA workflows use separate tasks, should be fixed by https://github.com/opensearch-project/opensearch-java/pull/968

**Comment by VachaShah** [comment]
@dblock @reta This is ready for review. I added samples and guides as well.

**Review by dblock — APPROVED** [review]
Looks good!

**Comment by dblock** [comment]
will need a manual backport pls
