### PR TITLE
Fixing issues when deserializing response for tasks API

### LINKED ISSUE #356: [BUG] deserializing the response of /_tasks endpoint fails because TaskExecutingNode.attributes is missing
### opensearch-java client version
2.2.0

### OpenSearch version
2.3 (Amazoon OpenSearch Service)

### Java version
11

### Problem description
In the response of the tasks endpoint the attribute `TaskExecutingNode.attributes` is missing. Since I didn't find any API specification I'm not sure if the attribute is missing in the response or if the client should not treat this attribute as mandatory.

### Request
GET /_tasks?actions=*reindex*

### Response
```
{
  "nodes": {
    "m5xFof7USZucap8drmTSkQ": {
      "name": "7abda77454688e5a695fc65aa63264b0",
      "roles": [
        "data",
        "ingest",
        "remote_cluster_client"
      ],
      "tasks": {
        "m5xFof7USZucap8drmTSkQ:4865054": {
          "node": "m5xFof7USZucap8drmTSkQ",
          "id": 4865054,
          "type": "transport",
          "action": "indices:data/write/reindex",
          "start_time_in_millis": 1675333077718,
          "running_time_in_nanos": 74025260228,
          "cancellable": true,
          "cancelled": false,
          "headers": {}
        }
      }
    }
  }
}
```

### Error message
```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'TaskExecutingNode.attributes'
        at org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:88) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.util.ApiTypeHelper.unmodifiableRequired(ApiTypeHelper.java:206) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.opensearch._types.BaseNode.<init>(BaseNode.java:70) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.opensearch.tasks.TaskExecutingNode.<init>(TaskExecutingNode.java:62) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.opensearch.tasks.TaskExecutingNode$Builder.build(TaskExecutingNode.java:148) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.opensearch.tasks.TaskExecutingNode$Builder.build(TaskExecutingNode.java:102) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:93) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:378) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.JsonpDeserializerBase$StringMapDeserializer.deserialize(JsonpDeserializerBase.java:364) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:85) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:189) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:150) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:320) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:286) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:143) ~[opensearch-java-2.2.0.jar!/:na]
        at org.opensearch.client.opensearch.tasks.OpenSearchTasksClient.list(OpenSearchTasksClient.java:153) ~[opensearch-java-2.2.0.jar!/:na]
        ...
```

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
Setting the task attributes to not required since Amazon OpenSearch Service does not return them as stated in #356.

### Issues Resolved
Closes #356 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/BaseNode.java [hunk 1]
```diff
@@ -180,7 +180,7 @@ protected void serializeInternal(JsonGenerator generator, JsonpMapper mapper) {
 		private String transportAddress;
 
 		/**
-		 * Required - API name: {@code attributes}
+		 * API name: {@code attributes}
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/opensearch/_types/BaseNode.java:183]: Minor, may be also add `@Nullable` to the fields as well? (like `roles`)

File: CHANGELOG.md [hunk 2]
```diff
@@ -23,6 +23,7 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
 ## [Unreleased 2.x]
 
 ### Added
+- Add workflow to publish snapshots via GHA ([#454](https://github.com/opensearch-project/opensearch-java/pull/454))
```
Comment (reta) [inline CHANGELOG.md:26]: Seems to be not related?

**Review by reta — APPROVED** [review]

**Review by reta — APPROVED** [review]

**Review by dblock — APPROVED** [review]
