### PR TITLE
Make `MultiSearchItem.status` optional

### LINKED ISSUE #520: [BUG] org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'MultiSearchItem.status'
### What is the bug?
multi search is not working with multisearch template but it does with regular multisearch using programatic query.
Error :
msearchTemplate() throws MissingRequiredPropertyException

```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'MultiSearchItem.status'
	at org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:88)
	at org.opensearch.client.opensearch.core.msearch.MultiSearchItem.<init>(MultiSearchItem.java:62)
	at org.opensearch.client.opensearch.core.msearch.MultiSearchItem$Builder.build(MultiSearchItem.java:119)
	at org.opensearch.client.opensearch.core.msearch.MultiSearchItem$Builder.build(MultiSearchItem.java:92)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:99)
	at org.opensearch.client.json.UnionDeserializer$SingleMemberHandler.deserialize(UnionDeserializer.java:91)
	at org.opensearch.client.json.UnionDeserializer.deserialize(UnionDeserializer.java:324)
	at org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:353)
	at org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:322)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:85)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:189)
	at org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:150)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:88)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92)
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56)
	at org.opensearch.client.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:69)
	at org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:325)
	at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:291)
	at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:144)
	at org.opensearch.client.opensearch.OpenSearchClient.msearchTemplate(OpenSearchClient.java:960)
```

### How can one reproduce the bug?
perform a multisearch openSearchClient.msearchTemplate() method

### What is the expected behavior?
Expected behavior is that there is a 200 response from opensearch with the results ready to be parsed

### What is your host/environment?
local docker with opensearch version 2.5.0 running in Mac Os using java client from kotlin

### Do you have any additional context?
Same issue was reported to elastic search here: 
https://github.com/elastic/elasticsearch-java/issues/110
and solved here:
https://github.com/elastic/elasticsearch-java/commit/4a0aa0826d73f5cb593b1c4a34346b02c3d15263

### PR DESCRIPTION
**Pull request by Xtansia**
### Description
Make `MultiSearchItem.status` optional as it is returned by regular msearch requests but not in msearchTemplate requests.

### Issues Resolved
Fixes #520 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: java-client/src/test/java/org/opensearch/client/opensearch/integTest/AbstractSearchTemplateRequestIT.java [hunk 1]
```diff
@@ -85,6 +85,31 @@ public void testTemplateSearchAggregations() throws Exception {
 
     }
 
+    @Test
+    public void testMultiSearchTemplate() throws Exception {
+        var index = "test-msearch-template";
+        createDocuments(index);
+
+        var searchResponse = javaClient().msearchTemplate(
```
Comment (VachaShah) [inline java-client/src/test/java/org/opensearch/client/opensearch/integTest/AbstractSearchTemplateRequestIT.java:93]: If a multi search template example is not present, it would be great to add it to the guides and working samples.

**Review by VachaShah — APPROVED** [review]

**Review by dblock — APPROVED** [review]
