### PR TITLE
Fixing partial success results for msearch template

### LINKED ISSUE #708: [BUG] MultiSearchTemplate partial success response is broken
### What is the bug?
A user reported: When a multisearch template request is sent to the client and if the request partially succeeds i.e. one or more templates in the request fails, instead of returning an error response for that particular item, the client fails with the below exception and discards all the results from that request.

```
org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'ErrorResponse.status'
        at __randomizedtesting.SeedInfo.seed([B7831F18B61D38F2:88DBA2B968F5C73E]:0)
        at app//org.opensearch.client.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:89)
        at app//org.opensearch.client.opensearch._types.ErrorResponse.<init>(ErrorResponse.java:72)
        at app//org.opensearch.client.opensearch._types.ErrorResponse$Builder.build(ErrorResponse.java:156)
        at app//org.opensearch.client.opensearch._types.ErrorResponse$Builder.build(ErrorResponse.java:119)
        at app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:98)
        at app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:60)
        at app//org.opensearch.client.json.UnionDeserializer$SingleMemberHandler.deserialize(UnionDeserializer.java:91)
        at app//org.opensearch.client.json.UnionDeserializer.deserialize(UnionDeserializer.java:326)
        at app//org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:343)
        at app//org.opensearch.client.json.JsonpDeserializerBase$ArrayDeserializer.deserialize(JsonpDeserializerBase.java:308)
        at app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
        at app//org.opensearch.client.json.ObjectDeserializer$FieldObjectDeserializer.deserialize(ObjectDeserializer.java:81)
        at app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:185)
        at app//org.opensearch.client.json.ObjectDeserializer.deserialize(ObjectDeserializer.java:146)
        at app//org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:87)
        at app//org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:91)
        at app//org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:55)
        at app//org.opensearch.client.transport.endpoints.EndpointWithResponseMapperAttr$1.deserialize(EndpointWithResponseMapperAttr.java:68)
        at app//org.opensearch.client.transport.rest_client.RestClientTransport.decodeResponse(RestClientTransport.java:322)
        at app//org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:288)
        at app//org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:148)
        at app//org.opensearch.client.opensearch.OpenSearchClient.msearchTemplate(OpenSearchClient.java:1006)
        at app//org.opensearch.client.opensearch.OpenSearchClient.msearchTemplate(OpenSearchClient.java:1022)
```

### How can one reproduce the bug?
Run msearch_template request where one or more templates would fail.

### What is the expected behavior?
All results from the server should be returned in this scenario.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
After investigating the issue, this happens because for `msearch` request, when one or more searches fail, the server returns a status:

```
{
      "took" : 601,
      "timed_out" : false,
      "_shards" : {
        "total" : 1,
        "successful" : 1,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : {
          "value" : 0,
          "relation" : "eq"
        },
        "max_score" : null,
        "hits" : [ ]
      },
      "status" : 200
    }
  ]
}
```

whereas for msearch_template it does not

```
{
  "took" : 2,
  "responses" : [
    {
      "took" : 2,
      "timed_out" : false,
      "_shards" : {
        "total" : 1,
        "successful" : 1,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : {
          "value" : 2,
          "relation" : "eq"
        },
        "max_score" : 0.6785375,
        "hits" : [
          {
            "_index" : "employees",
            "_id" : "2",
            "_score" : 0.6785375,
            "_source" : {
              "id" : 2,
              "name" : "Othilia Cathel",
              "email" : "ocathel1@senate.gov",
              "gender" : "female",
              "ip_address" : "3.164.153.228",
              "date_of_birth" : "22/07/1987",
              "company" : "Edgepulse",
              "position" : "Structural Engineer",
              "experience" : 11,
              "country" : "China",
              "phrase" : "Grass-roots heuristic help-desk",
              "salary" : 193530
            }
          },
          {
            "_index" : "employees",
            "_id" : "4",
            "_score" : 0.62577873,
            "_source" : {
              "id" : 4,
              "name" : "Alan Thomas",
              "email" : "athomas2@example.com",
              "gender" : "male",
              "ip_address" : "200.47.210.95",
              "date_of_birth" : "11/12/1985",
              "company" : "Yamaha",
              "position" : "Resources Manager",
              "experience" : 12,
              "country" : "China",
              "phrase" : "Emulation of roots heuristic coherent systems",
              "salary" : 300000
            }
          }
        ]
      },
      "aggregations" : {
        "test-aggs" : {
          "doc_count_error_upper_bound" : 0,
          "sum_other_doc_count" : 0,
          "buckets" : [
            {
              "key" : 193530,
              "doc_count" : 1
            },
            {
              "key" : 300000,
              "doc_count" : 1
            }
          ]
        }
      },
      "suggest" : {
        "test-suggest" : [
          {
            "text" : "heuristic",
            "offset" : 0,
            "length" : 9,
            "options" : [ ]
          }
        ]
      }
    },
    {
      "error" : {
        "root_cause" : [
          {
            "type" : "resource_not_found_exception",
            "reason" : "unable to find script [my-other-search-template] in cluster state"
          }
        ],
        "type" : "resource_not_found_exception",
        "reason" : "unable to find script [my-other-search-template] in cluster state"
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
Same as title

### Issues Resolved
Resolves #708

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java [hunk 1]
```diff
@@ -62,14 +62,14 @@ private enum Kind {
 
     private final ErrorCause error;
 
-    private final int status;
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: @VachaShah hm I believe `status` should be always present, we may have an issue on the server side?

Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: @reta I dug through the server side and the server itself does not return `status` for msearch template requests. (see additional context section in https://github.com/opensearch-project/opensearch-java/issues/708).

Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: The server does not set a status for MultiSearchTemplateResponse (https://github.com/opensearch-project/OpenSearch/blob/main/modules/lang-mustache/src/main/java/org/opensearch/script/mustache/MultiSearchTemplateResponse.java#L169) whereas for MultiSearchResponse, it does https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/search/MultiSearchResponse.java#L195.

Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: Do you think this is something that should be fixed on the server side? I am not sure if there is any history behind not setting status for mutli search templates 🤔

Comment (reta) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: Thanks a lot for digging it in @VachaShah !

> Do you think this is something that should be fixed on the server side?

I believe so, the status field should always be set by the server.

Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: Got it, thank you @reta! I think we should still merge this fix though so that the users can use it with the current versions of OpenSearch, WDYT?

Comment (reta) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: Oh that's right, no objection

**Review by reta — APPROVED** [review]

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java (hunk 1 above)
Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: Thank you! I will raise an issue on OpenSearch to add the status field for multi search templates.

**Review by dblock — APPROVED** [review]

File: java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java (hunk 1 above)
Comment (VachaShah) [reply java-client/src/main/java/org/opensearch/client/opensearch/_types/ErrorResponse.java:65]: @reta I opened an issue on the server for this: https://github.com/opensearch-project/OpenSearch/issues/11133
