### PR TITLE
Fixing integration tests

### LINKED ISSUE #374: [BUG] Integration tests failing against main branch of OpenSearch
### What is the bug?
Integration tests are failing against the main branch of OpenSearch.

https://github.com/opensearch-project/opensearch-java/actions/runs/4230299684/jobs/7347473860

### How can one reproduce the bug?
Follow https://github.com/opensearch-project/opensearch-java/blob/main/.github/workflows/test-integration-unreleased.yml

### What is the expected behavior?
Tests should run successfully.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
Fixing failing integration tests against OpenSearch main.

### Issues Resolved
Closes #374 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: java-client/src/test/java/org/opensearch/client/opensearch/integTest/AbstractClusterClientIT.java [hunk 1]
```diff
@@ -95,11 +103,19 @@ public void testClusterUpdateSettingNonExistent() throws IOException {
         } catch (OpenSearchException e) {
             assertNotNull(e);
             assertEquals(e.response().status(), 400);
-            assertEquals(
+            if (Version.fromString(version).onOrAfter(Version.fromString("3.0.0"))) {
+                assertEquals(
+                    e.getMessage(),
+                    "Request failed: [settings_exception] " +
```
Comment (reta) [inline java-client/src/test/java/org/opensearch/client/opensearch/integTest/AbstractClusterClientIT.java:109]: Do we need the exact match here? May be simpler check would be to ensure `"transient setting [no_idea_what_you_are_talking_about], not recognized"` is present?

**Review by reta — APPROVED** [review]

**Review by dblock — APPROVED** [review]
