### PR TITLE
FIX: catch 401 and 403 status and return proper error message

### LINKED ISSUE #494: [BUG] Failing to connect to an OpenSearch cluster with a bad username/password gives unhelpful error
### What is the bug?
Failing to connect to an OpenSearch cluster with a bad username/password gives unhelpful error:

```
Exception in thread "main" jakarta.json.stream.JsonParsingException: Jackson exception: Unrecognized token 'Unauthorized': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (ByteArrayInputStream); line: 1, column: 13]
	at org.opensearch.client.json.jackson.JacksonJsonpParser.convertException(JacksonJsonpParser.java:97)
	at org.opensearch.client.json.jackson.JacksonJsonpParser.fetchNextToken(JacksonJsonpParser.java:104)
	at org.opensearch.client.json.jackson.JacksonJsonpParser.next(JacksonJsonpParser.java:131)
	at org.opensearch.client.json.JsonpDeserializer.deserialize(JsonpDeserializer.java:82)
	at org.opensearch.client.json.ObjectBuilderDeserializer.deserialize(ObjectBuilderDeserializer.java:92)
	at org.opensearch.client.json.DelegatingDeserializer$SameType.deserialize(DelegatingDeserializer.java:56)
	at org.opensearch.client.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:271)
	at org.opensearch.client.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:143)
	at org.opensearch.client.opensearch.cluster.OpenSearchClusterClient.getSettings(OpenSearchClusterClient.java:282)
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.checkISMEnabled(AbstractIndexManager.java:187)
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.checkAndCreateIndexTemplate(AbstractIndexManager.java:208)
	at org.opensearch.dataprepper.plugins.sink.opensearch.index.AbstractIndexManager.setupIndex(AbstractIndexManager.java:203)
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.doInitializeInternal(OpenSearchSink.java:174)
	at org.opensearch.dataprepper.plugins.sink.opensearch.OpenSearchSink.doInitialize(OpenSearchSink.java:139)
	at org.opensearch.dataprepper.model.sink.AbstractSink.initialize(AbstractSink.java:39)
	at org.opensearch.dataprepper.pipeline.Pipeline.isReady(Pipeline.java:194)
	at org.opensearch.dataprepper.DataPrepper.execute(DataPrepper.java:93)
	at org.opensearch.dataprepper.DataPrepperExecute.main(DataPrepperExecute.java:42)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Unauthorized': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (ByteArrayInputStream); line: 1, column: 13]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:759)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3693)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2781)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:907)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:793)
	at org.opensearch.client.json.jackson.JacksonJsonpParser.fetchNextToken(JacksonJsonpParser.java:102)
	... 16 more
```

### How can one reproduce the bug?
use opensearch-java client with wrong username or password configured to call any API against a opensearch engine

### What is the expected behavior?
A clear error message indicating wrong username or password

### What is your host/environment?
macOS.

### Do you have any screenshots?
Screenshot 2023-05-22 at 1 28 29 PM

### Do you have any additional context?
The bug seems to be at parsing with both `RestClientTransport` and `AwsSdk2Transport`

### PR DESCRIPTION
**Pull request by chenqi0805**
### Description
This PR fixes the unclear 401 unauthorized exception by catching Json parsing exception.

### Issues Resolved
Closes #494 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java [hunk 1]
```diff
@@ -273,7 +274,7 @@ private <ResponseT, ErrorT> ResponseT getHighLevelResponse(
                         // TODO: have the endpoint provide the exception constructor
                         throw new OpenSearchException((ErrorResponse) error);
                     }
-                } catch(MissingRequiredPropertyException errorEx) {
+                } catch(MissingRequiredPropertyException | JsonParsingException errorEx) {
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java:277]: Should we better off handle the 401/403 separately? It seems like we should not be trying to parse the response entity as JSON knowing it is not the right content type:

```

HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="OpenSearch Security"
content-type: text/plain; charset=UTF-8
content-length: 12

```

File: java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+import java.io.IOException;
+import java.net.URISyntaxException;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertThrows;
+import static org.mockito.ArgumentMatchers.any;
+import static org.mockito.ArgumentMatchers.eq;
+import static org.mockito.Mockito.when;
+
+public class RestClientTransportTest {
```
Comment (reta) [inline java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java:41]: We don't need to mock that: the integration tests (fe AbstractRequestIT & co) do run against OS clusters w/o security, it is easy to trigger 401 by supplying invalid credentials (and probably even 403 by doing non-permissive action). Please let me know if you need help crafting these test cases.

File: java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java [hunk 3]
```diff
@@ -246,7 +247,11 @@ private <ResponseT, ErrorT> ResponseT getHighLevelResponse(
         try {
             int statusCode = clientResp.getStatusLine().getStatusCode();
 
-            if (endpoint.isError(statusCode)) {
+            if (statusCode == HttpStatusCode.FORBIDDEN) {
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java:250]: :+1

File: java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java [hunk 4]
```diff
@@ -60,6 +60,7 @@
 import org.opensearch.client.ResponseException;
 import org.opensearch.client.ResponseListener;
 import org.opensearch.client.RestClient;
+import software.amazon.awssdk.http.HttpStatusCode;
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java:63]: `HttpStatusCode` is not a right import

File: java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java (hunk 2 above)
Comment (chenqi0805) [reply java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java:41]: @reta Could you give me an example on the fastest way of instantiating OpenSearch Client with custom credential within AbstractRequestIT. Also could you provide an example of non-permissive action? I was thinking of wrong http method but since it is high-level API I would not be able to construct that

File: java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java [hunk 5]
```diff
@@ -32,6 +32,7 @@
 
 package org.opensearch.client.transport.rest_client;
 
+import org.apache.hc.core5.http.HttpStatus;
```
Comment (reta) [inline java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java:35]: This is still not right import, the `RestClientTransport` uses Apache HttpClient 4.x, please use `org.apache.http.HttpStatus`

File: java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java (hunk 2 above)
Comment (reta) [reply java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java:41]: Sure, will do that shortly

File: java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java (hunk 5 above)
Comment (chenqi0805) [reply java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java:35]: I did not see org.apache.http.HttpStatus in your dependency. Shall I add it explicitly?

Comment (reta) [reply java-client/src/main/java/org/opensearch/client/transport/rest_client/RestClientTransport.java:35]: My apologies @chenqi0805 , this is my bad, for `main` this is the right import, we would need to change it to the one I mentioned when backporting to 2.x

File: java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java (hunk 2 above)
Comment (reta) [reply java-client/src/test/java/org/opensearch/client/transport/rest_client/RestClientTransportTest.java:41]: @chenqi0805 here is a quick example to give you an idea, for `org.opensearch.client.opensearch.integTest.restclient.RequestIT` test suite:

```
@Test
    public void testUnauthorized() throws Exception {
        // The security plugin is required
        Assume.assumeThat(isHttps(), equalTo(true));

        final RestClient restClient = RestClient
            .builder(getClusterHosts().toArray(new HttpHost[0]))
            .setHttpClientConfigCallback(httpClientBuilder -> {
                try {
                    final TlsStrategy tlsStrategy = ClientTlsStrategyBuilder
                        .create()
                        .setSslContext(SSLContextBuilder.create().loadTrustMaterial(null, (chains, authType) -> true).build())
                        .setHostnameVerifier(NoopHostnameVerifier.INSTANCE)
                        .setTlsDetailsFactory(new Factory<SSLEngine, TlsDetails>() {
                            @Override
                            public TlsDetails create(final SSLEngine sslEngine) {
                                return new TlsDetails(sslEngine.getSession(), sslEngine.getApplicationProtocol());
                            }
                        })
                        .build();
    
                    final PoolingAsyncClientConnectionManager connectionManager = PoolingAsyncClientConnectionManagerBuilder.create()
                        .setTlsStrategy(tlsStrategy)
                        .build();
    
                    return httpClientBuilder.setConnectionManager(connectionManager);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            })
            .build();

        final RestClientTransport transport = new RestClientTransport(restClient, new JacksonJsonpMapper());
        final OpenSearchClient client = new OpenSearchClient(transport);
        client.nodes().info();
    }
```

When run against secured OS server (ether dockerized or not), it fails on `main` (without your changes) with:

```
jakarta.json.stream.JsonParsingException: Jackson exception: Unrecognized token 'Unauthorized': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (ByteArrayInputStream); line: 1, column: 13]
	at __randomizedtesting.SeedInfo.seed([2A1A3F446909C3E8:B38154320C47377F]:0)
	at org.opensearch.client.json.jackson.JacksonJsonpParser.convertException(JacksonJsonpParser.java:102)
...
```

**Review by reta — APPROVED** [review]

File: java-client/src/test/java/org/opensearch/client/opensearch/integTest/restclient/RequestIT.java [hunk 6]
```diff
@@ -9,17 +9,104 @@
...
     public OpenSearchTransport buildTransport(Settings settings, HttpHost[] hosts) throws IOException {
         return new RestClientTransport(buildClient(settings, hosts), new JacksonJsonpMapper());
     }
+
+    @Test
+    public void testUnauthorized() throws Exception {
+        // The security plugin is required
+        Assume.assumeThat(isHttps(), equalTo(true));
+
+        final String userName = Optional.ofNullable(System.getProperty("user")).orElse("admin");
```
Comment (reta) [inline java-client/src/test/java/org/opensearch/client/opensearch/integTest/restclient/RequestIT.java:53]: I think you don't even need `credentialsProvider` here

**Review by dblock — APPROVED** [review]
@reta you good with this?

**Comment by VachaShah** [comment]
@chenqi0805 It shows that you don't have a local 2.x branch. You can either checkout a 2.x branch on your local or use the branch from origin. Example: 

```
git fetch
git worktree add ../.worktrees/backport-2.x upstream/2.x
```

**Comment by reta** [comment]
Thanks @VachaShah , @chenqi0805 if you still have difficulties, I could do backport for you, thank you
